# Generated by Django 6.0.1 on 2026-02-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='datasets/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('data_json', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Uploaded Dataset',
                'verbose_name_plural': 'Uploaded Datasets',
                'ordering': ['-upload_date'],
            },
        ),
    ]
